server:
  port: 8084

spring:
  application:
    name: collab-service

  datasource:
    url: jdbc:mysql://localhost:3306/collab_service_db
    username: root
    password: keshav
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true


springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html