server:
  port: 8080

spring:
  application:
    name: auth-service

#  config:
#    import: "optional:file:.env[.properties]"

  datasource:
    url: jdbc:mysql://localhost:3306/users
    username: root
    password: keshav
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.security: DEBUG
    com.codesync.auth: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka